Update snyk_scan.yml

diff --git a/.github/workflows/snyk_scan.yml b/.github/workflows/snyk_scan.yml
--- a/.github/workflows/snyk_scan.yml
+++ b/.github/workflows/snyk_scan.yml
@@ -18,14 +18,19 @@ jobs:
         run: 
              length=$(cat snyk.sarif | jq '.runs[0].results | length')
              echo "RESULTS_LENGTH=$length" >>$GITHUB_ENV
-      - name : Pass_or_Fail_the_job
+      - name: Pass_or_Fail_the_job
         run: |
-            if [ "$RESULTS_LENGTH" != 0 ]; then
-                echo "Job Failed"
-                exit 1
-            else 
-                echo "Pass"
-            fi
+            if [ -z "$RESULTS_LENGTH" ]; then
+               echo "RESULTS_LENGTH is not set or is empty"
+               exit 1
+            elif [ "$RESULTS_LENGTH" != "0" ]; then
+               echo "Job Failed"
+               exit 1
+            else
+               echo "Pass"
+               fi
+        env:
+         RESULTS_LENGTH: ${{ secrets.RESULTS_LENGTH }}
 
       - name: Send notification on Slack using webhooks
         uses: slackapi/slack-github-action@v1.24.0
